---
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible ubuntu node
    ec2:
      key_name: Ansible
      instance_type: t2.micro
      image: ami-0fe48fc70a6a75c85
      wait: yes
      group: SSH
      region: us-east-2
      count: 2
      vpc_subnet_id: subnet-f84318b4
      assign_public_ip: yes
      instance_tags:
         Name: ubuntuservers 