---
-  hosts: 172.31.36.62
   become: yes
   tasks: 
   - name: i want webserver on Debian node
     apt:
      name: apache2
      state: present
     notify: restartwebserver 

   - name: i want copy index.j2 on Debian node
     template:
        src: index.j2
        dest: /var/www/html/index.html
     notify: restartwebserver
   handlers: 
   - name: restartwebserver
     service:
      name: apache2
      state: present