---
- hosts: 172.31.44.79 
  become: yes
  tasks:
  - name: i want to install git 
    apt:
      name: git
      state: present

      #  apt-get install git
      
  - name: i want to install tree
    apt:
      name: tree
      statee: present
    ignore_errors: yes

  - name: i want to install wget
    apt:
      name: wget
      state: present